### ISSUE TITLE
Update anndata to 0.7rc1

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/anndata-feedstock#3]
Hi,

There is a pre-release for "anndata", 0.7rc1. I was wondering if I can update the recipe to the new version using the "prerelease" channel.
If yes, is creating a new branch and adding "conda_config_build.yaml" in the recipe directory sufficient, or there are other steps to follow in order to include a pre-release?

Happy Holidays!

Thank you,
Natasha

**Comment by flying-sheep** [comment]
I have no idea how that works! Not a conda user myself. Maybe you can @ somebody who knows?

**Comment by JakaKokosar** [comment]
Yea, me neither. You can ask for help [here](https://gitter.im/conda-forge/conda-forge.github.io?source=orgpage).

**Comment by flying-sheep** [comment]
0.7 final is here
